## Command to build conda environment for Praison AI Framework, Agents, and Tools
## conda env create -f environment.yml
## conda activate praisonAI_apps

name: praisonAI_apps
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy<2.0
  - scipy>=1.1.0
  - pandas>=1.3.0
  - matplotlib>=1.4.0
  - seaborn>=0.7.1
  - scikit-learn>=0.16.1
  - bottleneck>=1.3.0
  - pip:
    # Core utilities
    - rich>=13.7
    - markdown>=3.5
    - pyparsing>=3.0.0
    - python-dotenv>=1.0.1
    - PyYAML>=6.0
    - flask>=2.0.0
    
    # PraisonAI packages
    - praisonaiagents>=0.0.4
    - praisonai_tools
    - praisonai
    - literalai
    
    # Web and Data Processing
    - webencodings
    - beautifulsoup4>=4.11.1
    - lxml>=4.9.1
    - html5lib
    - pytz>=2022.5
    - duckduckgo_search
    
    # Database and SQL
    - sqlalchemy>=2.0
    - ipython-sql
    - ipython-genutils
    
    # Optimization
    - cvxpy>=1.6.0
    - osqp>=0.6.7
    - qdldl>=0.1.7
    - scs>=3.2.7
    - clarabel>=0.9.0
    
    # Financial Analysis
    - yfinance
    - empyrical-reloaded>=0.5.11
    - pyfolio-reloaded>=0.9.8
    
    # SDK and Utils
    - instructor>=0.4.8
    - tenacity==8.2.3
    - traceloop-sdk>=0.38.5